name: RoundReviewPlugins_Stack

services:

# NOTE: comment out the following services that you don't want to run

  roundreview_pdf_notary_bot:
    container_name: "roundreview_pdf_notary_bot"
    build: ./plugins/pdf-notary-bot
    restart: unless-stopped
    ports: 
      - "8081:8081"
    volumes:
      - rr_signed_pdfs:/signed_pdfs
      # NOTE: Update this path according to the location of your certificates
      - ./certs:/certs
    env_file:
      - ./envs/rr-pdf-notary-bot.env

  roundreview_example_bot:
    container_name: "roundreview_example_bot"
    build: ./plugins/example-bot
    restart: unless-stopped
    ports: 
      - "8082:8082"
    environment:
      - DEBUG=1

volumes:
  rr_signed_pdfs: